### Makefile.cnf --- User level configuration

## Copyright (C) 2010, 2011, 2013 Didier Verna

## Author: Didier Verna <didier@didierverna.net>

## This file is part of Declt.

## Declt is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 3,
## as published by the Free Software Foundation.

## Declt is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


### Commentary:



### Code:

# Installation prefix. This is used as follows:
# - $(PREFIX)/share/doc/declt/ for the PDF documentation
# - $(PREFIX)/share/info/ for the info documentation
# If any of these are unsatisfactory, you will need to edit the Makefiles, or
# do the installation by hand.
PREFIX := /usr/local

# Preferred Common Lisp implementation.
# Choices are: SBCL.
LISP := SBCL

# Implementation paths:
SBCL_PATH := sbcl

# Programs required for generating the documentation:
MAKEINFO := makeinfo
TEXI2DVI := texi2dvi
TEXI2PDF := texi2pdf
DVIPS    := dvips
CONVERT  := convert

# Other required programs:
INSTALL := install
INSTALL-INFO := install-info


### Makefile.cnf ends here
